In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Advantages of Numpy arrays over Python List
# Save coding time - no loops, vector and matrix operations saves coding time
# Faster execution - uses contiguous blocks of memory. 
# The value is direclty stored in the memory address rather than a pointer
# Uses less memory - has no pointers unlike lists

In [3]:
# NumPy array pointers
# all elements have same numpy datatype
# memory size of each item in bytes
# dimensions of the array is the shape
# easiest way to access the data is through indexing

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
a = np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [9]:
a = np.linspace(1,12,6)
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [11]:
a.reshape(3,2)

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [13]:
a = a.reshape(3,2)
a

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [14]:
a.size

6

In [15]:
a.shape

(3, 2)

In [16]:
a.dtype

dtype('float64')

In [17]:
a.itemsize

8

In [18]:
a.max()

12.0

In [19]:
a.min()

1.0

In [20]:
a.mean()

6.5

In [21]:
a.var()

14.116666666666667

In [22]:
a.std()

3.757215280851853

In [23]:
a.sum(axis=0)

array([16.2, 22.8])

In [24]:
a.sum(axis=1)

array([ 4.2, 13. , 21.8])

In [26]:
a = np.arange(10)

In [27]:
np.random.shuffle(a)

In [28]:
np.random.choice(a)

5